### ISSUE TITLE
strange NullPointerException

### ISSUE THREAD

**Issue by bart-kors** [astefanutti/metrics-cdi#7]
Hi,

I am getting the following NullPointerException I am not able to debug it. Any idea how i can solve it?

```
Exception in thread "main" java.lang.RuntimeException: org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
Exception 0 :
java.lang.NullPointerException
	at com.codahale.metrics.MetricRegistry$Proxy$_$$_WeldClientProxy.buildMap(Unknown Source)
	at com.codahale.metrics.MetricRegistry.<init>(MetricRegistry.java:58)
	at com.codahale.metrics.MetricRegistry$Proxy$_$$_WeldClientProxy.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jboss.weld.bean.proxy.DefaultProxyInstantiator.newInstance(DefaultProxyInstantiator.java:43)
	at org.jboss.weld.bean.proxy.ProxyFactory.run(ProxyFactory.java:327)
	at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:319)
	at org.jboss.weld.bean.proxy.ClientProxyFactory.create(ClientProxyFactory.java:83)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:198)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:188)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.access$100(ClientProxyProvider.java:46)
	at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.load(ClientProxyProvider.java:57)
	at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.load(ClientProxyProvider.java:53)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:49)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:74)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:222)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:736)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:765)
	at org.jboss.weld.util.ForwardingBeanManager.getReference(ForwardingBeanManager.java:61)
	at org.jboss.weld.bean.builtin.BeanManagerProxy.getReference(BeanManagerProxy.java:85)
	at io.astefanutti.metrics.cdi.MetricsExtension.getReference(MetricsExtension.java:128)
	at io.astefanutti.metrics.cdi.MetricsExtension.getReference(MetricsExtension.java:123)
	at io.astefanutti.metrics.cdi.MetricsExtension.configuration(MetricsExtension.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:309)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:124)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:287)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:265)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:450)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:238)
	at org.jboss.weld.environment.servlet.Listener.contextInitialized(Listener.java:121)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:198)
	at com.dopay.backend.cms.web.bootstrap.UndertowWebServer.deployAndStart(UndertowWebServer.java:53)
	at com.dopay.backend.cms.web.bootstrap.UndertowWebServer.start(UndertowWebServer.java:47)
	at com.dopay.backend.cms.web.bootstrap.UndertowWebServer$Proxy$_$$_WeldClientProxy.start(Unknown Source)
	at com.dopay.backend.cms.web.CustomerService.main(CustomerService.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:309)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:287)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:265)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:136)
	at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:673)
	at org.jboss.weld.environment.se.WeldContainer.initialize(WeldContainer.java:144)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:562)
	at org.jboss.weld.environment.se.StartMain.go(StartMain.java:44)
	at org.jboss.weld.environment.se.StartMain.main(StartMain.java:53)

	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:231)
	at com.dopay.backend.cms.web.bootstrap.UndertowWebServer.deployAndStart(UndertowWebServer.java:53)
	at com.dopay.backend.cms.web.bootstrap.UndertowWebServer.start(UndertowWebServer.java:47)
	at com.dopay.backend.cms.web.bootstrap.UndertowWebServer$Proxy$_$$_WeldClientProxy.start(Unknown Source)
	at com.dopay.backend.cms.web.CustomerService.main(CustomerService.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:309)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:287)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:265)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:136)
	at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:673)
	at org.jboss.weld.environment.se.WeldContainer.initialize(WeldContainer.java:144)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:562)
	at org.jboss.weld.environment.se.StartMain.go(StartMain.java:44)
	at org.jboss.weld.environment.se.StartMain.main(StartMain.java:53)
```

**Comment by astefanutti** [comment]
@bart-kors hum hard to tell like that :(

What version of Weld are you using? Have you tried with the latest `2.3.3.Final` version and the latest Metrics CDI `1.3.3` version?

It looks like an issue when Weld is creating a contextual reference / proxy for the `MetricRegistry` class. But I fail to see why that call to the protected `buildMap` method in the default constructor would throw a NPE.

Maybe you could write a small test, without using Metrics CDI at all, having just a `MetricRegistry` bean, and getting a proxy for it in the same setup.

**Comment by astefanutti** [comment]
Let me close that issue as I presume you may have found a way-around. Do no hesitate to re-open it if needed.
