### ISSUE TITLE
Exception when deploying application to Wildfly 9.0.2

### ISSUE THREAD

**Issue by lucasweb78** [astefanutti/metrics-cdi#8]
I have added metics-cdi 1.3.3 to my WAR that I deploy to Wildfly 9.0.2.Final and am seeing the following exception at deploy time:
```
javax.enterprise.event.ObserverException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:96)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:306)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:121)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:284)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:262)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:54)
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:447)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:94)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.IllegalAccessError: tried to access class com.codahale.metrics.MetricRegistry$MetricBuilder from class com.codahale.metrics.MetricRegistry$Proxy$_$$_WeldClientProxy
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:49)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:74)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:222)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:755)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:784)
	at org.jboss.weld.util.ForwardingBeanManager.getReference(ForwardingBeanManager.java:61)
	at org.jboss.weld.bean.builtin.BeanManagerProxy.getReference(BeanManagerProxy.java:85)
	at io.astefanutti.metrics.cdi.MetricsExtension.getReference(MetricsExtension.java:128)
	at io.astefanutti.metrics.cdi.MetricsExtension.getReference(MetricsExtension.java:123)
	at io.astefanutti.metrics.cdi.MetricsExtension.configuration(MetricsExtension.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	... 20 more
Caused by: java.lang.IllegalAccessError: tried to access class com.codahale.metrics.MetricRegistry$MetricBuilder from class com.codahale.metrics.MetricRegistry$Proxy$_$$_WeldClientProxy
	at com.codahale.metrics.MetricRegistry$Proxy$_$$_WeldClientProxy.<clinit>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jboss.weld.bean.proxy.DefaultProxyInstantiator.newInstance(DefaultProxyInstantiator.java:43)
	at org.jboss.weld.bean.proxy.ProxyFactory.run(ProxyFactory.java:307)
	at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:299)
	at org.jboss.weld.bean.proxy.ClientProxyFactory.create(ClientProxyFactory.java:83)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:198)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:188)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.access$100(ClientProxyProvider.java:46)
	at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.load(ClientProxyProvider.java:57)
	at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.load(ClientProxyProvider.java:53)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 38 more
```

**Comment by astefanutti** [comment]
This corresponds to [WELD-2083](https://issues.jboss.org/browse/WELD-2092) that has been fixed with [WELD-2092](https://issues.jboss.org/browse/WELD-2092) in Weld version `2.3.3.Final`. I'm bit surprised you hit the issue in WildFly as I originally faced the issue in OSGi environments though the stack trace matches.

The proper fix for the issue would be to patch your WildFly instances with Weld version `2.3.3.Final`.

A work-around would to declare a `MetricRegistry` bean in your application with the `@Singleton` scope so that no proxy gets created, e.g.:
```
@Produces
@Singleton
MetricRegistry registry = new MetricRegistry();
```

**Comment by lucasweb78** [comment]
I went with the work-around for now which resolves the issue at deploy time. Patching is not really an option as I do not have control of the Wildfly instances the application is deployed to.

It appears the issues above impact WELD 2.2.16.SP1 and Wildfly 9.0.2

With the work-around I am able to deploy my application and use the JMX Reporter. 

I have run into one issue with this approach. If I want to inject the registry into a class I need to provide an additional annotation on the producer e.g. @MyCustomAnnotation and use that along with the @Inject annotation. This does appear to work but when I do this I do not see any of the metrics registered with the registry but the name and listeners match.

I'm running into this issue when trying to inject the registry into a ServletListnerContext so that I can use the metric-servlets. Do you think this issue is related to the work-around or is it something different?

**Comment by astefanutti** [comment]
Metrics CDI looks up for a `MetricRegistry` bean with the `@Default` qualifier. So if you add a qualifier to your `MetricsRegistry` producer, it won't take it into account unless your explicitly add the `@Default` qualifier, e.g.:
```
@Produces
@Singleton
@Default
@MyQualifier
MetricRegistry registry = new MetricRegistry();
```

**Comment by lucasweb78** [comment]
The qualifier was a red-hearing. I mistakenly had two MetricRegistry producers in my code base for a short period and that was causing the issue. Once I resolved that I has able to Inject the Metric Registry in the the Metric Servlet and it works as expected.

One additional question, does the metrics-cdi work with the HealthCheckRegistry?

**Comment by astefanutti** [comment]
Metrics CDI doesn't automatically add a `HealthCheckRegistry` bean and register the `HealthCheck` beans for the time being. That would be quite easy to add support for that, as it's quite similar to what's being done for the `MetricRegistry` and `Metric` beans.

I'll try to work on that ASAP. In the meantime, feel free to create a new ticket to track that development. And if you feel like contributing that'd be even better :smile:.

**Comment by astefanutti** [comment]
I've just created #13 to track progress on the `HealthCheckRegistry` support.
